load("//internal_tools:build_defs.bzl", "gbbs_cc_test")

gbbs_cc_test(
    name = "seq_test",
    srcs = ["seq_test.cc"],
    deps = [
        "//pbbslib:seq",
        "@googletest//:gtest_main",
    ],
)
