cc_library(
  name = "counting_sort_no_transpose",
  hdrs = ["counting_sort_no_transpose.h"],
  deps = ["//ligra:bridge"]
)

cc_library(
  name = "dyn_arr",
  hdrs = ["dyn_arr.h"],
  deps = ["//ligra:bridge"]
)

cc_library(
  name = "resizable_table",
  hdrs = ["resizable_table.h"],
  deps = ["//ligra:bridge"]
)

cc_library(
  name = "sparse_additive_map",
  hdrs = ["sparse_additive_map.h"],
  deps = ["//ligra:bridge"]
)

cc_library(
  name = "sparse_table",
  hdrs = ["sparse_table.h"],
  deps = ["//ligra:bridge"]
)

package(
  default_visibility = ["//visibility:public"],
)
