cc_library(
    name = "string_basics",
    hdrs = ["string_basics.h"],
    deps = [
        "//pbbslib:maybe",
        "//pbbslib:sequence",
    ],
)

package(
    default_visibility = ["//visibility:public"],
)
