load("//internal_tools:build_defs.bzl", "gbbs_cc_library")

gbbs_cc_library(
    name = "string_basics",
    srcs = ["string_basics.cc"],
    hdrs = ["string_basics.h"],
    deps = [
        "//pbbslib:sequence",
    ],
)

package(
    default_visibility = ["//visibility:public"],
)
