load("@pybind11_bazel//:build_defs.bzl", "pybind_extension", "pybind_library")

pybind_extension(
  name = "vertex_subset",
  srcs = ["vertex_subset.cc"],
  deps = [
      "//ligra:vertex_subset",
  ],
)
