cc_test(
    name = "graph_test",
    srcs = ["graph_test.cc"],
    deps = [
        "//ligra:graph",
        "//ligra:graph_test_utils",
        "//pbbslib:seq",
        "@googletest//:gtest_main",
    ],
)

cc_test(
    name = "undirected_edge_test",
    srcs = ["undirected_edge_test.cc"],
    deps = [
        "//ligra:undirected_edge",
        "@googletest//:gtest_main",
    ],
)
