cc_test(
    name = "graph_filter_test",
    srcs = ["graph_filter_test.cc"],
    deps = [
      "//ligra:ligra",
      "//ligra:graph",
      "//ligra/semiasym:graph_filter",
      "//ligra:graph_test_utils",
      "//pbbslib:seq",
      "@googletest//:gtest_main",
    ],
)

package(
  default_visibility = ["//visibility:public"],
)
